name: ftr-deploy.yml
on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - 'feature/**'
jobs:
  package:
    name: Build and Push
    environment: dev
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    outputs:
      image_tag: ${{ steps.set_image_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate Docker to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west2-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set image tag
        id: set_image_tag
        run: |
          # Use a consistent and unique tag, like the commit SHA
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        env:
          PROJECT_ID: pa-rf-sandbox
          REPOSITORY: rf-pa-dev-docker-registry
          IMAGE_NAME: my-r-app-image
        run: |
          IMAGE_TAG=${{ steps.set_image_tag.outputs.IMAGE_TAG }}
          docker build -t europe-west2-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG .
          docker push europe-west2-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG

  deploy:
    name: Deploy to Cloud Run
    needs:
      - package
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch workflow and log response
        run: |
          
          echo image-tag = ${{needs.build.outputs.image_tag}}
          
          # Create a temporary file to store the API response body
          response_file=$(mktemp)

          # Execute curl, writing the HTTP status code to a variable and the body to the temp file
          http_status_code=$(curl -s -w "%{http_code}" -L \
            -o "$response_file" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}"\
            https://api.github.com/repos/fensomer-pa/test-terraform-gcp/actions/workflows/crj-dev-deploy.yml/dispatches \
            -d '{"ref":"feature/testing-tf","inputs":{"pipeline_name":"stats-intermediate-to-canonical", "environment_name":"ftr", "image_tag":"${{needs.build.outputs.image_tag}}"}}'
          )

          echo "API response status code: $http_status_code"
          echo "--- API Response Body ---"
          cat "$response_file"
          echo "-------------------------"

          # Fail the step if the status code is not a success (2xx)
          if [ "$http_status_code" -lt 200 ] || [ "$http_status_code" -ge 300 ]; then
            echo "Error: API call failed with status code $http_status_code"
            exit 1
          fi

          echo "Successfully triggered workflow. View runs at: https://github.com/fensomer-pa/test-terraform-gcp/actions/workflows/crj-dev-deploy.yml"
