name: ftr-deploy.yml
on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - 'feature/**'

permissions:
  contents: 'read'
  id-token: 'write'

env:
  VERSION: ${{ github.sha }}
  PROJECT_ID: pa-rf-sandbox
  REPOSITORY: rf-pa-dev-docker-registry
  IMAGE_NAME: my-r-app-image

jobs:
  build:
    name: Build and Test
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker ${{ vars.GCP_IMAGE_REGISTRY_HOST }}

      - name: Build Image
        run: |
          docker build -t europe-west2-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} .

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: europe-west2-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Push Image
        run: docker push europe-west2-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}


  deploy:
    name: Trigger Deployment Workflow
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch workflow and log response
        run: |
          # Create a temporary file to store the API response body
          response_file=$(mktemp)

          # Execute curl, writing the HTTP status code to a variable and the body to the temp file
          http_status_code=$(curl -s -w "%{http_code}" -L \
            -o "$response_file" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}"\
            https://api.github.com/repos/fensomer-pa/test-terraform-gcp/actions/workflows/crj-dev-deploy.yml/dispatches \
            -d '{"ref":"feature/testing-tf","inputs":{"pipeline_name":"stats-intermediate-to-canonical", "environment_name":"ftr", "image_tag":"europe-west2-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}"}}'
          )

          echo "API response status code: $http_status_code"
          echo "--- API Response Body ---"
          cat "$response_file"
          echo "-------------------------"

          # Fail the step if the status code is not a success (2xx)
          if [ "$http_status_code" -lt 200 ] || [ "$http_status_code" -ge 300 ]; then
            echo "Error: API call failed with status code $http_status_code"
            exit 1
          fi

          echo "Successfully triggered workflow. View runs at: https://github.com/fensomer-pa/test-terraform-gcp/actions/workflows/crj-dev-deploy.yml"
